// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  // Sidebar for the ROS 2 module
  ros2ModuleSidebar: [
     {
      type: 'doc',
      id: 'physical-ai-intro', // docs/introduction.md file
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'ros2-module/intro-to-ros2',
        'ros2-module/communication-model',
        'ros2-module/urdf-structure',
      ],
    },
  // Sidebar for the Digital Twin module
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'digital-twin-module/intro',
        'digital-twin-module/physics-simulation',
        'digital-twin-module/unity-hri',
        'digital-twin-module/sensor-simulation',
        'digital-twin-module/summary',
        'digital-twin-module/assessment',
        'digital-twin-module/glossary',
      ],
  
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'ai-robot-brain-module/isaac-sim-synthetic-data',
        'ai-robot-brain-module/isaac-ros-perception',
        'ai-robot-brain-module/nav2-navigation',
        'ai-robot-brain-module/summary',
        'ai-robot-brain-module/assessment',
        'ai-robot-brain-module/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'vla-module/intro',
        'vla-module/vla-foundations',
        'vla-module/voice-commands-llm-planning',
        'vla-module/capstone-autonomous-humanoid',
        'vla-module/summary',
        'vla-module/assessment',
        'vla-module/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Module 5: Sensor Systems',
      items: [
        'module-5-sensor-systems/fundamentals',
        'module-5-sensor-systems/sensor-types',
        'module-5-sensor-systems/sensor-types-classification',
        'module-5-sensor-systems/sensor-integration',
        'module-5-sensor-systems/sensor-integration-pipeline',
        'module-5-sensor-systems/perception-pipeline-flow',
        'module-5-sensor-systems/environmental-awareness-coverage',
        'module-5-sensor-systems/example-scenarios',
        'module-5-sensor-systems/assessments',
        'module-5-sensor-systems/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Module 6: Locomotion',
      items: [
        'module-6-locomotion/fundamentals',
        'module-6-locomotion/gait-balance-stability',
        'module-6-locomotion/planning-control',
        'module-6-locomotion/example-scenarios',
        'module-6-locomotion/assessments',
        'module-6-locomotion/glossary'
      ],
    },
  ],
};

export default sidebars;
